</$objtype/mkfile

CC=pcc
CFLAGS=-I. -B -c -DPLAN9

LIB=libimcomm.a$O

OFILES= \
	bos_signon.$O\
	flap.$O\
	imcomm.$O\
	md5.$O\
	misc.$O\
	packet.$O\
	proxy.$O\
	snac.$O\

</sys/src/cmd/mklib

install:V:	$LIB
	date

$LIB:	$LIBOBJ
	ar vu $LIB $OFILES
	
clean:
	rm -f *.[$OS] *.a[$OS]
